sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: video
        field:
          display: Video
          type: video
          icon: video
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: thumbnail
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          display: Thumbnail
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: client
        field:
          input_type: text
          antlers: false
          display: Client
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: location
        field:
          input_type: text
          antlers: false
          display: Location
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: date
        field:
          mode: single
          time_enabled: false
          time_seconds_enabled: false
          full_width: false
          inline: false
          columns: 1
          rows: 1
          display: Date
          type: date
          icon: date
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: content
        field:
          collapse: false
          always_show_set_button: false
          previews: true
          smart_typography: false
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
          save_html: false
          inline: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          antlers: false
          remove_empty_nodes: false
          display: Content
          type: bard
          icon: bard
          listable: hidden
          instructions_position: above
          visibility: visible
      -
        handle: template
        field:
          hide_partials: true
          blueprint: false
          display: Template
          type: template
          icon: template
          listable: hidden
          instructions_position: above
          visibility: visible
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
title: Project
